name: manual-release

on:
  workflow_dispatch:
    inputs:
      api_version:
        required: false
        description: Interscript API release version, default equals "gem_interscript_version"
      gem_interscript_version:
        required: true
        description: Interscript Gem version that published to "rubygems.org"

env:
  GITHUB_PUSH_TOKEN: ${{ secrets.INTERSCRIPT_CI_PAT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  API_VERSION: ${{github.event.inputs.api_version}}
  INTERSCRIPT_VERSION: ${{github.event.inputs.gem_interscript_version}}

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: clone it
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: setup env vars
        run: |
          API_VERSION="${API_VERSION:-$INTERSCRIPT_VERSION}"
          echo "API_VERSION=$API_VERSION" >> ${GITHUB_ENV}

      - name: debug
        run: |
          echo "API_VERSION=$API_VERSION"
          echo "INTERSCRIPT_VERSION=$INTERSCRIPT_VERSION"

      - name: make new release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{env.GITHUB_PUSH_TOKEN}}
        with:
          tag_name: v${{env.API_VERSION}}
          release_name: Release API for Interscript Gem v${{env.INTERSCRIPT_VERSION}}
          body: for Interscript Gem v${{env.INTERSCRIPT_VERSION}}
          draft: false
          prerelease: false
