name: release-tag

on:
  repository_dispatch:
    types: [ interscript/interscript ]

jobs:
  push-tag:
    runs-on: ubuntu-18.04
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v1
    - name: Add writable remote
      run: |
        git config --global user.name "interscript-ci"
        git config --global user.email "interscript-ci@users.noreply.github.com"
        git remote add github "https://metanorma-ci:${{ secrets.INTERSCRIPT_CI_PAT }}@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
    - name: Parse interscript version
      env:
        INTERSCRIPT_TAG: ${{ github.event.client_payload.ref }}
      run: |
        echo "::set-env name=INTERSCRIPT_VERSION::${INTERSCRIPT_TAG#*/v}"
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install bundler
      run: |
        gem install bundler
    - name: Update version
      run: |
        bundle remove interscript
        bundle add interscript -v ${INTERSCRIPT_VERSION}
        bundle install --deployment
    - name: Push commit and tag
      run: |
        git add Gemfile
        git commit -m "Bump version to ${INTERSCRIPT_VERSION}.0"
        git tag v${INTERSCRIPT_VERSION}.0
        git push github HEAD:${GITHUB_REF} --tags